steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-app/customer:$SHORT_SHA', 'customer']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-app/customer:$SHORT_SHA']
# Specify options. Since this build trigger specifies SA, logging option must be specified.  
- name: 'gcr.io/$PROJECT_ID/kustomize'
  dir:  'customer/kustomize'
  entrypoint: bash
  args:
  - '-c'
  - |
    kustomize edit set image changeonbuild=$$IMAGE_NAME && kustomize build > kustomized_service.yaml
  env:
    - 'IMAGE_NAME=${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-app/customer:$SHORT_SHA'
- name: 'ubuntu'
  dir:  'customer/kustomize'
  args: ['cat', 'kustomized_service.yaml']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir:  'customer/kustomize'
  entrypoint: gcloud
  args:
    - 'run'
    - 'services'
    - 'replace'
    - 'kustomized_service.yaml'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
substitutions:
  _REGION: us-central1    
options:
  logging: CLOUD_LOGGING_ONLY
