steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer:$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/customer:$SHORT_SHA']
# Specify options. Since this build trigger specifies SA, logging option must be specified.  
 options:
  logging: CLOUD_LOGGING_ONLY
