apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-dep
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        resources: 
          requests:
            cpu: "500m"
          limits:
            cpu: "500m"
            memory: "1Gi"
        image: asia-south1-docker.pkg.dev/gcdeveloper/customer/customer:v1
        env:
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongouri
                key: SPRING_DATA_MONGODB_URI