apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/gcdeveloper/demo-app/customer:4dad9b3
        resources:
          limits:
            cpu: "2"
