apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: customer
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: cloudrun-vpc-con
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: "1"
              name: mongouri-customer
        image: us-central1-docker.pkg.dev/gcdeveloper/demo-app/customer:d6e5949
        resources:
          limits:
            cpu: "1"
